# Optimizer Configuration (shared across regions)
# Sprint 0 - Section 1 specs (frozen)
# QP-based portfolio construction with risk/cost models

# Core identifiers
random_state: 42

# Risk model
risk_model: "barra_like"
cov_shrinkage: "ledoit_wolf"

# Objective function parameters
objective:
  gamma: 8.0          # risk aversion coefficient; RL can overwrite in S3+
  lambda1: 5.0e-4     # L1 turnover penalty; RL can overwrite in S3+
  lambda2: 2.0e-6     # L2 impact penalty; RL can overwrite in S3+

# Turnover constraints
turnover:
  tau: 0.25           # max turnover as fraction of NAV per day; RL can overwrite in S3+

# Position bounds
bounds:
  long_only: true
  per_name: [0.0, 0.02]           # per-stock min/max weight
  per_industry: [-0.05, 0.05]     # per-industry exposure bands

# Volatility target
vol_target:
  base: 0.12          # annualized portfolio volatility target; RL can overwrite in S3+

# Industry regime tilts (S0: not used; S1+: Model 1 inputs)
regime_tilts:
  kappa_trend_bp: 10  # tilt scale in basis points for Bull vs Bear
